//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenericRepositoryPattern.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCQ
    {
        public int MCQSId { get; set; }
        public string Statment { get; set; }
        public string A { get; set; }
        public string B { get; set; }
        public string C { get; set; }
        public string D { get; set; }
        public string Ans { get; set; }
        public bool Board { get; set; }
        public string BoardName { get; set; }
        public bool Exercise { get; set; }
        public bool Book { get; set; }
        public int ChaptertId { get; set; }
        public int SubjectId { get; set; }
        public int ClasstId { get; set; }
    
        public virtual Chapter Chapter { get; set; }
        public virtual Class Class { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
